export const expected = {
  name: "Minted",
  type: "dark",
  semanticHighlighting: true,
  colors: {
    "editor.background": "#090910ff",
    "editor.foreground": "#545c7ee6",
    "sideBar.background": "#0a0a10",
    "tree.indentGuidesStroke": "#36367099",
    "tree.inactiveIndentGuidesStroke": "#12121add",
    "tab.inactiveBackground": "#0c0c13ff",
    "sideBar.foreground": "#515b76c9",
    "gitDecoration.modifiedResourceForeground": "#7786b7f4",
    "gitDecoration.addedResourceForeground": "#86cebeea",
    "gitDecoration.conflictingResourceForeground": "#f09fb7ea",
    "gitDecoration.deletedResourceForeground": "#f09fadea",
    "gitDecoration.ignoredResourceForeground": "#454d61c9",
    "gitDecoration.renamedResourceForeground": "#9fa0f0ea",
    "gitDecoration.untrackedResourceForeground": "#82809df2",
    "gitDecoration.stageDeletedResourceForeground": "#704752f4",
    "gitDecoration.stageModifiedResourceForeground": "#f0de9fea",
    "editorGutter.addedBackground": "#468a74cf",
    "minimapGutter.addedBackground": "#264b3f",
    "gitlens.decorations.addedForegroundColor": "#9ff0e3ea",
    "diffEditorGutter.insertedLineBackground": "#011211e2",
    "diffEditor.insertedLineBackground": "#010e0daa",
    "diffEditor.insertedTextBackground": "#112b2a42",
    "diffEditor.insertedTextBorder": "#142f2a22",
    "diffEditorGutter.removedLineBackground": "#2d0a12b4",
    "diffEditor.removedLineBackground": "#0f0404",
    "diffEditor.removedTextBorder": "#300e1622",
    "diffEditor.removedTextBackground": "#20030cbb",
  },
};
