import { Color } from "../../src/core/color";
import { apatheticOcean } from "../../src/themes/apatheticOcean";
import { apathy } from "../../src/themes/apathy";
import { apathyExperimental } from "../../src/themes/apathyExperimental";
import { minted } from "../../src/themes/minted";
import { mintedTheory } from "../../src/themes/mintedTheory";
import { slate } from "../../src/themes/slate";

const outputPath = new URL(
	"../../src/themes/themePaths.generated.ts",
	import.meta.url,
);

const themeSources = [
	apathy,
	apatheticOcean,
	apathyExperimental,
	minted,
	mintedTheory,
	slate,
];

const additionalObjectPaths = ["ui.window"] as const;

const additionalLeafPaths = [
	"tokens.operators.arithmetic",
	"tokens.operators.assignment",
	"tokens.operators.bitwise",
	"tokens.operators.comparison",
	"tokens.operators.logical",
	"tokens.operators.wordlike",
	"ui.highlights.word.border",
	"ui.icon.disabled",
	"ui.icon.muted",
	"ui.peekView.matchHighlightBackground",
	"ui.peekView.titleDescriptionForeground",
	"ui.window.activeBorder",
	"ui.window.inactiveBorder",
] as const;

type JsonObject = Record<string, unknown>;

function isPlainObject(value: unknown): value is JsonObject {
	if (value === null || typeof value !== "object") {
		return false;
	}
	if (value instanceof Color || Array.isArray(value)) {
		return false;
	}
	const prototype = Object.getPrototypeOf(value);
	return prototype === Object.prototype || prototype === null;
}

function cloneValue(value: unknown): unknown {
	if (Array.isArray(value)) {
		return value.map((item) => cloneValue(item));
	}
	if (isPlainObject(value)) {
		return Object.fromEntries(
			Object.entries(value).map(([key, child]) => [key, cloneValue(child)]),
		);
	}
	return value;
}

function mergeValues(base: unknown, next: unknown): unknown {
	if (!isPlainObject(base) || !isPlainObject(next)) {
		return cloneValue(next);
	}

	const merged: JsonObject = Object.fromEntries(
		Object.entries(base).map(([key, value]) => [key, cloneValue(value)]),
	);

	for (const [key, value] of Object.entries(next)) {
		merged[key] =
			key in merged ? mergeValues(merged[key], value) : cloneValue(value);
	}

	return merged;
}

function collectPaths(
	value: unknown,
	prefix = "",
	allPaths = new Set<string>(),
	leafPaths = new Set<string>(),
): { allPaths: Set<string>; leafPaths: Set<string> } {
	if (!isPlainObject(value)) {
		return { allPaths, leafPaths };
	}

	for (const [key, child] of Object.entries(value)) {
		// Dot-path helpers split on ".", so keys containing dots are not addressable.
		if (key.includes(".")) {
			continue;
		}

		const path = prefix ? `${prefix}.${key}` : key;
		allPaths.add(path);

		if (isPlainObject(child)) {
			collectPaths(child, path, allPaths, leafPaths);
		} else {
			leafPaths.add(path);
		}
	}

	return { allPaths, leafPaths };
}

function formatType(name: string, values: string[]): string {
	if (values.length === 0) {
		return `export type ${name} = never;\n`;
	}

	return [
		`export type ${name} =`,
		...values.map((value) => `\t| ${JSON.stringify(value)}`),
		";",
		"",
	].join("\n");
}

const mergedTheme = themeSources.reduce<unknown>(
	(accumulator, theme) => mergeValues(accumulator, theme),
	{},
);
const { allPaths, leafPaths } = collectPaths(mergedTheme);

for (const path of additionalObjectPaths) {
	allPaths.add(path);
}

for (const path of additionalLeafPaths) {
	allPaths.add(path);
	leafPaths.add(path);
}

const themePaths = [...allPaths].sort();
const themeColorPaths = [...leafPaths].sort();
const uiPaths = themePaths
	.filter((path) => path.startsWith("ui."))
	.map((path) => path.slice(3))
	.sort();

const output = [
	"/**",
	" * Auto-generated by `bun run generate:theme-paths`.",
	" * Do not edit this file by hand.",
	" */",
	"",
	formatType("ThemePath", themePaths),
	formatType("ThemeColorPath", themeColorPaths),
	formatType("UIPath", uiPaths),
].join("\n");

await Bun.write(outputPath, output);

console.log(
	`Generated ${themePaths.length} theme paths, ${themeColorPaths.length} leaf paths, and ${uiPaths.length} ui paths.`,
);
